development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: redis://redistogo:6148ed463b2d5d4c53f30a9e014e7e0c@pearlfish.redistogo.com:10356/
  channel_prefix: uwucord_app_production
  # url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
